### PR TITLE
Package `dioxus-desktop-template` for linux

### PR DESCRIPTION
**Pull request by shivaraj-bh**
Tasks

- Linux bundling -- to be resolved in a separate PR
- [x] use `wrapProgram` to change dir to `assets`

### CODE REVIEW

**Comment by shivaraj-bh** [comment]
CSS renders on my NixOS using: https://github.com/tauri-apps/tauri/issues/4315#issuecomment-1207804495

But the warning for DBus still remains, which according to this [comment](https://github.com/tauri-apps/tauri/issues/4315#issuecomment-1180262039), can be ignored.

**Comment by shivaraj-bh** [comment]
The error while bundling `AppImage` is very vague, it just says `error while running appimage.sh`. I couldn't find more details even after using `--verbose`. 

Looked for it in `tauri`'s source code, and:
This shell script is located at `dist/bundle/appimage/build_appimage.sh` (created by tauri), I tried running this script manually and came across this:
```
-- Running input plugin: gtk -- 
[gtk/stdout] Installing AppRun hook
[gtk/stderr] chmod: cannot access 'dioxus-desktop-template.AppDir/usr/lib64': No such file or directory
[gtk/stdout] Installing GLib schemas
[gtk/stderr] cp: cannot stat '/nix/store/1c6x8n47mq5rcivsp72b0dyqgjghi6yx-glib-2.76.4/share/glib-2.0/schemas': No such file or directory
ERROR: Failed to run plugin: gtk (exit code: 1)
```
Looks like `gtk` is looking for `schemas` at the wrong location, it should be looking in the nix-store path of `glib-2.76.4-dev` instead.

**Comment by srid** [comment]
Does `nix run` work on Linux (NixOS or otherwise)?

**Comment by shivaraj-bh** [comment]
> Does `nix run` work on Linux (NixOS or otherwise)?

Works on NixOS when packaged to run with `WEBKIT_DISABLE_COMPOSITING_MODE=1`

**Comment by srid** [comment]
> Works on NixOS when packaged to run with `WEBKIT_DISABLE_COMPOSITING_MODE=1`

Seems to be a general problem (not limited to our app): https://github.com/NixOS/nixpkgs/issues/32580

So we can just document this in the README without worrying about fixing it ourselves.

However, what's the behaviour when this env is not set? What happens when you open the app? Can you post screenshots? Is there a way to we can tell the user to set this env when this happens?

**Comment by srid** [comment]
@shivaraj-bh If `nix run` works on Linux (with or without that env var set) and macOS, I'd like to merge this PR in its current state (with suitable README updates), with the bundle/AppImage work happening in subsequent PRs.

**Comment by shivaraj-bh** [comment]
> Can you post screenshots?

Screenshot from 2023-10-05 at 23_42_55 063299170

Looks like CSS assets don't get applied

**Comment by srid** [comment]
I saw that too, but c83468e355ec2e146903920d0644b1514728d018 fixed it for me on macOS. Maybe the way dioxus looks for assets is different on Linux?

`nix run` on macOS:

image

**Comment by shivaraj-bh** [comment]
> If nix run works on Linux

I just wanted to confirm with Ubuntu, which I will do tomorrow, I might find one in the office. 

> I'd like to merge this PR in its current state (with suitable README updates)

I am cool with that!

> with the bundle/AppImage work happening in subsequent PRs.

👍

**Comment by shivaraj-bh** [comment]
> Maybe the way dioxus looks for assets is different on Linux?

I doubt its that, the fact that it works when I use `WEBKIT_DISABLE_COMPOSITING_MODE=1` means that it is failing when webkit is trying to use GPU to accelerate the rendering.

**Comment by shivaraj-bh** [comment]
Tried it on Ubuntu, had to use `WEBKIT_DISABLE_COMPOSITING_MODE=1` even there.

App without env is a blank screen (in NixOS at least the text was rendered)
Screenshot from 2023-10-06 16-00-17

Loads fine with the Env while inside `bin` (`cd ./result/bin && WEBKIT_DISABLE_COMPOSITING_MODE=1 ./dioxus-desktop-template`):
Screenshot from 2023-10-06 15-57-16

**Comment by shivaraj-bh** [comment]
> Maybe the way dioxus looks for assets is different on Linux?


You were right, in linux it is looking for `tailwind.css` and other assets in the directory where you exec `nix run`.

The blank screen is because of `WEBKIT_DISABLE_COMPOSITING_MODE=1` (which only happens in Ubuntu and not on NixOS).

**Comment by shivaraj-bh** [comment]
@srid I couldn't find a straightforward way to fix this and hence added a workaround here: https://github.com/shivaraj-bh/dioxus-desktop-template/commit/8ba3a7e1fd970b9f695bb591883e5f04cf4a23fd

**Comment by srid** [comment]
> @srid I couldn't find a straightforward way to fix this and hence added a workaround here: [shivaraj-bh@8ba3a7e](https://github.com/shivaraj-bh/dioxus-desktop-template/commit/8ba3a7e1fd970b9f695bb591883e5f04cf4a23fd)

I believe you can improve this workaround by using `makeWrapper` in the the original package itself defined here, via `postFixup` and `makeWrapper`: https://github.com/srid/dioxus-desktop-template/blob/b3ea97807180f482df18c7487bebfa826783cdb4/nix/flake-module.nix#L94-L100

In particular the `--chdir` option https://github.com/NixOS/nixpkgs/blob/ba10489eae3b2b2f665947b516e7043594a235c8/pkgs/build-support/setup-hooks/make-wrapper.sh#L22C3-L22C11

see https://gist.github.com/CMCDragonkai/9b65cbb1989913555c203f4fa9c23374

I don't have a graphical Linux system - otherwise I'd try this myself. (Perhaps I should run Arm linux VM on my mac ...)

**Pull request merged**
