### PR TITLE
Cross build attempt

### LINKED ISSUE #11: Cross-compile to Windows
It would be great to be able to produce Windows `.exe`s (either via `justfile` or `nix` commands)

cf. https://discourse.nixos.org/t/cross-compile-rust-for-windows/9582/1

### PR DESCRIPTION
**Pull request by srid**
Resolves #11 

- [ ] make it build
- [ ] test it on a windows machine
- [ ] separate out cross build from default package

### CODE REVIEW

**Comment by srid** [comment]
Currently stuck by:

```
dioxus-desktop-template> error: linking with `cc` failed: exit status: 1
dioxus-desktop-template>   |
dioxus-desktop-template>   = note: LC_ALL="C" PATH="/nix/store/h4n26bs4xn52fz4nyw50knr8idnmxksx-rust-default-1.72.1/lib/rustlib/x86_64-unknown-linux-gnu/bin:/nix/store/5glndyjns6zg8kzwq6k84y6rfi83c4jz-x86_64-w64-mingw32-stage-final-gcc-wrapper-12.3.0/bin:/nix/store/35bmmvw09c9gzi98f86k1dfrx54l6sq5-x86_64-w64-mingw32-stage-final-gcc-12.3.0/bin:/nix/store/y9gr7abwxvzcpg5g73vhnx1fpssr5frr-coreutils-9.3/bin:/nix/store/yq08p0nhhpnjck1hq4i8ma6ah99gp4v2-x86_64-w64-mingw32-binutils-wrapper-2.40/bin:/nix/store/4d3rv899i6and7d835pms4mcahkvaixf-x86_64-w64-mingw32-binutils-2.40/bin:/nix/store/br1ssg4z8chk2yc7pb1n7xff1jz7l5dw-mcfgthreads-x86_64-w64-mingw32-git/bin:/nix/store/18bs92p6yf6w2wwxhbplgx02y6anq092-gcc-wrapper-12.3.0/bin:/nix/store/h5kvfrjmpw792v8jg7nrzfkffmn0iyy8-gcc-12.3.0/bin:/nix/store/f6in5kb2y5v06zinz1a6xy6cyg67q026-glibc-2.37-8-bin/bin:/nix/store/mc6q3cdz5s0p1aj4y586bglsfsnsf2k8-binutils-wrapper-2.40/bin:/nix/store/74y3751gsixaz9797ib0hp7c658sp1y5-binutils-2.40/bin:/nix/store/5daca24rn22c65ff25lc6z0g0imfphvr-pkg-config-wrapper-0.29.2/bin:/nix/store/prin9gyilbn5azgz407rj4wzgwyv917h-tailwindcss-3.3.3/bin:/nix/store/idsc5f2x5pyvbzq9pv3fl45rr8ghdxyg-dioxus-cli-0.4.1/bin:/nix/store/3lwrcxnxvfskh7m98fq0n5kqj2001ci7-jq-1.7-bin/bin:/nix/store/h4n26bs4xn52fz4nyw50knr8idnmxksx-rust-default-1.72.1/bin:/nix/store/0s2bzpml283zkfnhw7qi5qy1zlisffxj-rsync-3.2.7/bin:/nix/store/33vlrbngipikrfyhgyrpjars5qrjacj2-zstd-1.5.5-bin/bin:/nix/store/5p7jmbpmq7clb3whbi6kyp50gmg54l2d-zstd-1.5.5/bin:/nix/store/ay0p9mbw1w3zkvwzx3c94xq7x8jrn9wq-patchelf-0.15.0/bin:/nix/store/y9gr7abwxvzcpg5g73vhnx1fpssr5frr-coreutils-9.3/bin:/nix/store/b6izr8wh0p7dyvh3cyg14wq2rn8d31ik-findutils-4.9.0/bin:/nix/store/q56n7lhjw724i7b33qaqra61p7m7c0cd-diffutils-3.10/bin:/nix/store/x23by79p38ll0js1alifmf3y56vqfs49-gnused-4.9/bin:/nix/store/xafzciap7acqhfx84dvqkp18bg4lrai3-gnugrep-3.11/bin:/nix/store/8kkn44iwdbgqkrj661nr4cjcpmrqqmx8-gawk-5.2.2/bin:/nix/store/89s3w7b4g78989kpzc7sy4phv0nqfira-gnutar-1.35/bin:/nix/store/2a9na7bp4r3290yqqzg503325dwglxyq-gzip-1.13/bin:/nix/store/gxknjk51s7q86llkbzpaqv43kflj9d8j-bzip2-1.0.8-bin/bin:/nix/store/2jp6cv2q4cgh91f5lp57p945rq98ldhr-gnumake-4.4.1/bin:/nix/store/xdqlrixlspkks50m9b0mpvag65m3pf2w-bash-5.2-p15/bin:/nix/store/c15ama0p8jr4mn0943yjk4rpa2hxk7ml-patch-2.7.6/bin:/nix/store/sb3sxnp4g40gfw758a0m4sjm7slvmax9-xz-5.4.4-bin/bin:/nix/store/xfjqspcc9442hi0lm0szv3sw75zswvml-file-5.45/bin" VSLANG="1033" "cc" "-m64" "/build/rustcdXqYca/symbols.o" "/build/source/target/release/build/num-traits-7dfe166f86d896c8/build_script_build-7dfe166f86d896c8.build_script_build.116992ae8ef3b213-cgu.0.rcgu.o" "/build/source/target/release/build/num-traits-7dfe166f86d896c8/build_script_build-7dfe166f86d896c8.55rmq4zqqra7idd2.rcgu.o" "-Wl,--as-needed" "-L" "/build/source/target/release/deps" "-L" "/nix/store/h4n26bs4xn52fz4nyw50knr8idnmxksx-rust-default-1.72.1/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/nix/store/7y8rbg7qdi0fyq662vdkliibjwcgplf0-dioxus-desktop-template-deps-0.1.0/target/release/deps/libautocfg-c4909cdce4c40507.rlib" "/nix/store/magdha56w0swi3j1g1ja11ac4pllngq7-rust-std-1.72.1-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-b850d2b001350814.rlib" "/nix/store/magdha56w0swi3j1g1ja11ac4pllngq7-rust-std-1.72.1-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-a3d926e3ce38f6cc.rlib" "/nix/store/magdha56w0swi3j1g1ja11ac4pllngq7-rust-std-1.72.1-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-0a660adf51e0d01c.rlib" "/nix/store/magdha56w0swi3j1g1ja11ac4pllngq7-rust-std-1.72.1-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-49252de8bfa771e2.rlib" "/nix/store/magdha56w0swi3j1g1ja11ac4pllngq7-rust-std-1.72.1-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-6f52a21444f37c70.rlib" "/nix/store/magdha56w0swi3j1g1ja11ac4pllngq7-rust-std-1.72.1-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-57e8575f0ca731a2.rlib" "/nix/store/magdha56w0swi3j1g1ja11ac4pllngq7-rust-std-1.72.1-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-da4065b9a8ae7be4.rlib" "/nix/store/magdha56w0swi3j1g1ja11ac4pllngq7-rust-std-1.72.1-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-1ad47776352198ff.rlib" "/nix/store/magdha56w0swi3j1g1ja11ac4pllngq7-rust-std-1.72.1-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-7075f8a8dc932a7c.rlib" "/nix/store/magdha56w0swi3j1g1ja11ac4pllngq7-rust-std-1.72.1-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-a494eb4ddbb000f0.rlib" "/nix/store/magdha56w0swi3j1g1ja11ac4pllngq7-rust-std-1.72.1-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-672778ed8628861b.rlib" "/nix/store/magdha56w0swi3j1g1ja11ac4pllngq7-rust-std-1.72.1-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-9bba1c59dcc21440.rlib" "/nix/store/magdha56w0swi3j1g1ja11ac4pllngq7-rust-std-1.72.1-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-b9849fb628ce12eb.rlib" "/nix/store/magdha56w0swi3j1g1ja11ac4pllngq7-rust-std-1.72.1-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-0ea4fcc08eb96f77.rlib" "/nix/store/magdha56w0swi3j1g1ja11ac4pllngq7-rust-std-1.72.1-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-a8ba743c059cc198.rlib" "/nix/store/magdha56w0swi3j1g1ja11ac4pllngq7-rust-std-1.72.1-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-e4195ee2443e1656.rlib" "/nix/store/magdha56w0swi3j1g1ja11ac4pllngq7-rust-std-1.72.1-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-04991604e2730fd6.rlib" "/nix/store/magdha56w0swi3j1g1ja11ac4pllngq7-rust-std-1.72.1-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-f02db372677d4667.rlib" "/nix/store/magdha56w0swi3j1g1ja11ac4pllngq7-rust-std-1.72.1-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-448eba810c83029d.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/nix/store/h4n26bs4xn52fz4nyw50knr8idnmxksx-rust-default-1.72.1/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/build/source/target/release/build/num-traits-7dfe166f86d896c8/build_script_build-7dfe166f86d896c8" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs"
dioxus-desktop-template>   = note: /nix/store/74y3751gsixaz9797ib0hp7c658sp1y5-binutils-2.40/bin/ld: /nix/store/c28ynk0c4i3255a5g66iwglvc9c8jf8q-pthreads-w32-x86_64-w64-mingw32-2.9.1/lib/libpthread.a(pthread.o):(.text+0x21): undefined reference to `__imp_GetThreadContext'
dioxus-desktop-template>           /nix/store/74y3751gsixaz9797ib0hp7c658sp1y5-binutils-2.40/bin/ld: /nix/store/c28ynk0c4i3255a5g66iwglvc9c8jf8q-pthreads-w32-x86_64-w64-mingw32-2.9.1/lib/libpthread.a(pthread.o):(.text+0x3c): undefined reference to `__imp_SetThreadContext'
dioxus-desktop-template>           /nix/store/74y3751gsixaz9797ib0hp7c658sp1y5-binutils-2.40/bin/ld: /nix/store/c28ynk0c4i3255a5g66iwglvc9c8jf8q-pthreads-w32-x86_64-w64-mingw32-2.9.1/lib/libpthread.a(pthread.o):(.text+0xbe): undefined reference to `__imp_SetEvent'
dioxus-desktop-template>           /nix/store/74y3751gsixaz9797ib0hp7c658sp1y5-binutils-2.40/bin/ld: /nix/store/c28ynk0c4i3255a5g66iwglvc9c8jf8q-pthreads-w32-x86_64-w64-mingw32-2.9.1/lib/libpthread.a(pthread.o):(.text+0xd2): undefined reference to `__imp_CreateEventA'
dioxus-desktop-template>           /nix/store/74y3751gsixaz9797ib0hp7c658sp1y5-binutils-2.40/bin/ld: /nix/store/c28ynk0c4i3255a5g66iwglvc9c8jf8q-pthreads-w32-x86_64-w64-mingw32-2.9.1/lib/libpthread.a(pthread.o):(.text+0xeb): undefined reference to `__imp_CloseHandle'
```

https://jenkins.srid.ca/job/dioxus-desktop-template/job/cross/1/consoleText

---

## Solution 

https://discourse.nixos.org/t/cross-compiling-to-mingw-missing-libraries/31849/2?u=srid

**Comment by shivaraj-bh** [comment]
@srid I didn't notice that you were working on this.

I had initially built the app in #12 with `x86_64-pc-windows-gnu` and observed that the app failed in runtime as mentioned here: https://github.com/srid/dioxus-desktop-template/pull/12#issue-1955967272

**Comment by srid** [comment]
Oh, no problem. I was just trying it out briefly, not really focused on it or anything. Appreciate your efforts here. This is something I need only for my personal project: https://github.com/srid/felicity (I know someone that uses Windows that may be interested in trying this app out).

**Comment by srid** [comment]
> I had initially built the app in #12 with `x86_64-pc-windows-gnu` and observed that the app failed in runtime as mentioned here: [#12 (comment)](https://github.com/srid/dioxus-desktop-template/pull/12#issue-1955967272)

I just setup a Windows VM on my macOS, and yes I see this too. Your approach may be what we should go with ...

**Comment by shivaraj-bh** [comment]
Oh, and by the way with the latest commit (atm a workaround) on #12 you can build the app and see the error go away (CI is failing for some other reason).

CSS doesn't load but that can be fixed by shipping the app with the assets.

**Comment by srid** [comment]
> by the way with the latest commit (atm a workaround) on #12 you can build the app and see the error go away

This is what I see on my freshly installed Windows VM:

image

(Not sure what windows users are expected to do here ... install VS Runtime?)

**Comment by srid** [comment]
Maybe it is to do with me running x64 binary on arm windows. Okay, installing the visual studio 2015 runtime fixed it ...

**Comment by srid** [comment]
Closing in favour of #12

**Pull request closed without merging**
